#!/usr/bin/env python3
import gzip
import io
import os
import shutil
import tarfile
from pathlib import Path

PKG_NAME = "luci-app-emmc-health"
VERSION = "1.1.2"
RELEASE = "r1"
ARCH = "noarch"

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
OUT = DIST / f"{PKG_NAME}-{VERSION}-{RELEASE}.apk"

PKGINFO = f"""# Generated by luci-app-emmc-health build-apk.py
pkgname = {PKG_NAME}
pkgver = {VERSION}-{RELEASE}
pkgdesc = LuCI support for viewing eMMC EXT_CSD health information.
url = https://openwrt.org/
builddate = 0
packager = OpenWrt LuCI Community
size = 0
arch = {ARCH}
license = Apache-2.0
"""

POST_INSTALL = """#!/bin/sh

chmod 0755 /usr/libexec/emmc-health 2>/dev/null || true

if ! command -v mmc >/dev/null 2>&1 && command -v apk >/dev/null 2>&1; then
\t/bin/sh -c '
\t\tsleep 8
\t\techo "[luci-app-emmc-health] delayed mmc-utils install started"
\t\tapk update
\t\tapk add mmc-utils
\t\tif [ -x /etc/init.d/rpcd ]; then
\t\t\t/etc/init.d/rpcd reload 2>/dev/null || /etc/init.d/rpcd restart 2>/dev/null || true
\t\tfi
\t\tif [ -x /etc/init.d/uhttpd ]; then
\t\t\t/etc/init.d/uhttpd reload 2>/dev/null || /etc/init.d/uhttpd restart 2>/dev/null || true
\t\tfi
\t\techo "[luci-app-emmc-health] delayed mmc-utils install finished"
\t' >/tmp/luci-app-emmc-health-apk.log 2>&1 </dev/null &
fi

if [ -x /etc/init.d/rpcd ]; then
\t/etc/init.d/rpcd reload 2>/dev/null || /etc/init.d/rpcd restart 2>/dev/null || true
fi

if [ -x /etc/init.d/uhttpd ]; then
\t/etc/init.d/uhttpd reload 2>/dev/null || /etc/init.d/uhttpd restart 2>/dev/null || true
fi

exit 0
"""


def add_bytes(tar: tarfile.TarFile, name: str, data: bytes, mode: int) -> None:
	info = tarfile.TarInfo(name)
	info.size = len(data)
	info.mode = mode
	info.uid = 0
	info.gid = 0
	info.uname = "root"
	info.gname = "root"
	info.mtime = 0
	tar.addfile(info, io.BytesIO(data))


def add_dir(tar: tarfile.TarFile, name: str, seen: set) -> None:
	name = name.rstrip("/") + "/"
	if name in seen:
		return
	seen.add(name)
	info = tarfile.TarInfo(name)
	info.type = tarfile.DIRTYPE
	info.mode = 0o755
	info.uid = 0
	info.gid = 0
	info.uname = "root"
	info.gname = "root"
	info.mtime = 0
	tar.addfile(info)


def ensure_parent_dirs(tar: tarfile.TarFile, name: str, seen: set) -> None:
	name = name.replace("\\", "/").strip("/")
	while name.startswith("./"):
		name = name[2:]
	if not name:
		return
	current = "."
	for part in name.split("/")[:-1]:
		current = f"{current}/{part}"
		add_dir(tar, current, seen)


def add_tree(tar: tarfile.TarFile, source: Path, target_prefix: str, seen: set) -> None:
	for path in sorted(source.rglob("*")):
		rel = path.relative_to(source).as_posix()
		target = f"{target_prefix.rstrip('/')}/{rel}".replace("//", "/")
		ensure_parent_dirs(tar, target, seen)
		if path.is_dir():
			add_dir(tar, target, seen)
		else:
			mode = 0o755 if target == "./usr/libexec/emmc-health" else 0o644
			add_bytes(tar, target, path.read_bytes(), mode)


def main() -> None:
	DIST.mkdir(exist_ok=True)
	raw = io.BytesIO()
	seen = set()

	with tarfile.open(fileobj=raw, mode="w", format=tarfile.USTAR_FORMAT) as tar:
		add_bytes(tar, ".PKGINFO", PKGINFO.encode("utf-8"), 0o644)
		add_bytes(tar, ".post-install", POST_INSTALL.encode("utf-8"), 0o755)
		add_dir(tar, ".", seen)
		add_tree(tar, ROOT / "root", ".", seen)
		add_tree(tar, ROOT / "htdocs", "./www", seen)

	with OUT.open("wb") as f:
		with gzip.GzipFile(filename="", mode="wb", fileobj=f, mtime=0) as gz:
			gz.write(raw.getvalue())

	print(OUT)


if __name__ == "__main__":
	main()
